const SUPABASE_URL = "https://enpjshkrnvsjjndvsbxa.supabase.co";
const SUPABASE_ANON_KEY = "sb_publishable_yrZLgnczeJHQN9gJ3Dkmgw_Jvvf8gEj";
const db = (!SUPABASE_URL.includes("YOUR_")&&!SUPABASE_ANON_KEY.includes("YOUR_")) ? window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY) : null;
let shelters=[], journeys=[], activities=[], teamMembers=[];
const $=s=>document.querySelector(s);
const escapeHTML=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const categoryName=c=>({food:"Thức ăn",medical:"Y tế",volunteer:"Tình nguyện",supplies:"Vật dụng"}[c]||c);
function msg(t){$("#loginMessage").textContent=t}
async function ensureAdmin(){
 if(!db){msg("⚠️ Hãy cấu hình Supabase trong admin.js.");return false}
 const {data:{user}}=await db.auth.getUser();
 if(!user){$("#loginBox").classList.remove("hidden");$("#adminApp").classList.add("hidden");return false}
 const {data:p}=await db.from("profiles").select("role,full_name").eq("id",user.id).maybeSingle();
 if(p?.role!=="admin"){await db.auth.signOut();msg("Tài khoản này không có quyền admin.");return false}
 $("#loginBox").classList.add("hidden");$("#adminApp").classList.remove("hidden");$("#adminUser").textContent=`Đang đăng nhập: ${p.full_name||user.email}`;return true;
}
async function login(e){e.preventDefault();if(!db){msg("⚠️ Chưa cấu hình Supabase.");return}msg("Đang đăng nhập...");const {error}=await db.auth.signInWithPassword({email:$("#email").value.trim(),password:$("#password").value});if(error){msg("Đăng nhập thất bại: "+error.message);return}if(await ensureAdmin())await refresh()}
async function refresh(){await loadShelters();await loadContactEmail();await loadVolunteers();await loadProject();await loadJourneys();await loadActivities();await loadTeamMembers()}
async function loadShelters(){const {data,error}=await db.from("shelters").select("*").order("created_at",{ascending:false});if(error){alert(error.message);return}shelters=data||[];renderShelters()}
function renderShelters(){$("#adminShelterList").innerHTML=shelters.map(s=>`<div class="admin-item"><div><strong>${escapeHTML(s.name)}</strong><div>${escapeHTML(s.location)} · ${escapeHTML(categoryName(s.category))}</div></div><div class="admin-actions"><button class="small-btn" data-edit="${s.id}">Sửa</button><button class="small-btn danger" data-delete="${s.id}">Xóa</button></div></div>`).join("")||"<p>Chưa có trại cứu hộ.</p>"}
function editShelter(id){const s=shelters.find(x=>x.id===id);if(!s)return;$("#shelterId").value=s.id;$("#shelterName").value=s.name;$("#shelterLocation").value=s.location;$("#shelterCategory").value=s.category;$("#shelterTag").value=s.tag||"";$("#shelterImage").value=s.image||"";$("#shelterDescription").value=s.description;$("#shelterNeed").value=s.need;window.scrollTo({top:0,behavior:"smooth"})}
async function saveShelter(e){e.preventDefault();const id=$("#shelterId").value;const payload={name:$("#shelterName").value.trim(),location:$("#shelterLocation").value.trim(),category:$("#shelterCategory").value,tag:$("#shelterTag").value.trim(),image:$("#shelterImage").value.trim(),description:$("#shelterDescription").value.trim(),need:$("#shelterNeed").value.trim()};const {error}=id?await db.from("shelters").update(payload).eq("id",id):await db.from("shelters").insert(payload);if(error){alert(error.message);return}resetForm();await loadShelters()}
function resetForm(){$("#shelterForm").reset();$("#shelterId").value=""}
async function deleteShelter(id){if(!confirm("Xóa trại cứu hộ này?"))return;const {error}=await db.from("shelters").delete().eq("id",id);if(error)alert(error.message);else loadShelters()}
async function loadContactEmail(){const {data}=await db.from("site_settings").select("contact_email").eq("id",1).maybeSingle();$("#contactEmailInput").value=data?.contact_email||"hello@example.com"}
async function saveContactEmail(){const email=$("#contactEmailInput").value.trim();if(!email||!email.includes("@")){$("#emailMessage").textContent="Vui lòng nhập email hợp lệ.";return}const {error}=await db.from("site_settings").upsert({id:1,contact_email:email},{onConflict:"id"});$("#emailMessage").textContent=error?"Có lỗi: "+error.message:"✅ Đã cập nhật email liên hệ."}
async function loadVolunteers(){const {data,error}=await db.from("volunteers").select("*").order("created_at",{ascending:false});if(error){$("#volunteerList").textContent=error.message;return}$("#volunteerList").innerHTML=(data||[]).map(v=>`<div class="admin-item"><div><strong>${escapeHTML(v.name)}</strong> · ${escapeHTML(v.email)}<div>${escapeHTML(v.help)}${v.message?` · ${escapeHTML(v.message)}`:""}</div></div><button class="small-btn danger" data-volunteer-delete="${v.id}">Xóa</button></div>`).join("")||"<p>Chưa có đăng ký.</p>"}

async function loadProject(){const {data,error}=await db.from("project_content").select("*").eq("id",1).maybeSingle();if(error){$("#projectMessage").textContent=error.message;return}if(data){$("#projectTitleInput").value=data.title||"";$("#projectContentInput").value=data.content||"";$("#projectImageInput").value=data.image||"";$("#projectTagsInput").value=(data.tags||[]).join(", ")}}
async function saveProject(e){e.preventDefault();const payload={id:1,title:$("#projectTitleInput").value.trim(),content:$("#projectContentInput").value.trim(),image:$("#projectImageInput").value.trim(),tags:$("#projectTagsInput").value.split(",").map(x=>x.trim()).filter(Boolean),updated_at:new Date().toISOString()};const {error}=await db.from("project_content").upsert(payload,{onConflict:"id"});$("#projectMessage").textContent=error?"Có lỗi: "+error.message:"✅ Đã lưu giới thiệu dự án."}

async function loadJourneys(){const {data,error}=await db.from("journey_items").select("*").order("sort_order",{ascending:true}).order("created_at",{ascending:true});if(error){$("#adminJourneyList").textContent=error.message;return}journeys=data||[];renderJourneys()}
function renderJourneys(){$("#adminJourneyList").innerHTML=journeys.map(x=>`<div class="admin-item"><div><strong>${escapeHTML(x.number_label||"")} ${escapeHTML(x.title)}</strong><div>${escapeHTML(x.description)}</div><small>Thứ tự: ${x.sort_order}</small></div><div class="admin-actions"><button class="small-btn" data-journey-edit="${x.id}">Sửa</button><button class="small-btn danger" data-journey-delete="${x.id}">Xóa</button></div></div>`).join("")||"<p>Chưa có mốc hành trình.</p>"}
function editJourney(id){const x=journeys.find(v=>v.id===id);if(!x)return;$("#journeyId").value=x.id;$("#journeyNumber").value=x.number_label||"";$("#journeyTitle").value=x.title;$("#journeyImage").value=x.image||"";$("#journeyDescription").value=x.description;$("#journeyOrder").value=x.sort_order;document.querySelector('#journeyForm').scrollIntoView({behavior:'smooth',block:'center'})}
async function saveJourney(e){e.preventDefault();const id=$("#journeyId").value;const payload={number_label:$("#journeyNumber").value.trim(),title:$("#journeyTitle").value.trim(),description:$("#journeyDescription").value.trim(),image:$("#journeyImage").value.trim(),sort_order:Number($("#journeyOrder").value)||0,updated_at:new Date().toISOString()};const {error}=id?await db.from("journey_items").update(payload).eq("id",id):await db.from("journey_items").insert(payload);if(error){alert(error.message);return}resetJourney();await loadJourneys()}
function resetJourney(){$("#journeyForm").reset();$("#journeyId").value="";$("#journeyOrder").value=1}
async function deleteJourney(id){if(!confirm("Xóa mốc hành trình này?"))return;const {error}=await db.from("journey_items").delete().eq("id",id);if(error)alert(error.message);else loadJourneys()}


async function loadTeamMembers(){const {data,error}=await db.from("team_members").select("*").order("sort_order",{ascending:true}).order("created_at",{ascending:true});if(error){$("#adminTeamList").textContent=error.message;return}teamMembers=data||[];renderTeamMembers()}
function renderTeamMembers(){$("#adminTeamList").innerHTML=teamMembers.map(x=>`<div class="admin-item"><div style="display:flex;gap:12px;align-items:center">${x.image?`<img src="${escapeHTML(x.image)}" alt="" style="width:52px;height:52px;border-radius:50%;object-fit:cover">`:`<div style="width:52px;height:52px;border-radius:50%;display:grid;place-items:center;background:var(--bg);font-size:22px">🐾</div>`}<div><strong>${escapeHTML(x.name)}</strong><div>${escapeHTML(x.role)}</div><small>${escapeHTML(x.bio)}</small><br><small>Thứ tự: ${x.sort_order}</small></div></div><div class="admin-actions"><button class="small-btn" data-team-edit="${x.id}">Sửa</button><button class="small-btn danger" data-team-delete="${x.id}">Xóa</button></div></div>`).join("")||"<p>Chưa có thành viên.</p>"}
function editTeamMember(id){const x=teamMembers.find(v=>v.id===id);if(!x)return;$("#teamId").value=x.id;$("#teamName").value=x.name||"";$("#teamRole").value=x.role||"";$("#teamImage").value=x.image||"";$("#teamBio").value=x.bio||"";$("#teamOrder").value=x.sort_order||0;document.querySelector('#teamForm').scrollIntoView({behavior:'smooth',block:'center'})}
async function saveTeamMember(e){e.preventDefault();const id=$("#teamId").value;const payload={name:$("#teamName").value.trim(),role:$("#teamRole").value.trim(),image:$("#teamImage").value.trim(),bio:$("#teamBio").value.trim(),sort_order:Number($("#teamOrder").value)||0,updated_at:new Date().toISOString()};const {error}=id?await db.from("team_members").update(payload).eq("id",id):await db.from("team_members").insert(payload);if(error){alert(error.message);return}resetTeam();await loadTeamMembers()}
function resetTeam(){$("#teamForm").reset();$("#teamId").value="";$("#teamOrder").value=1}
async function deleteTeamMember(id){if(!confirm("Xóa thành viên này?"))return;const {error}=await db.from("team_members").delete().eq("id",id);if(error)alert(error.message);else loadTeamMembers()}

async function loadActivities(){const {data,error}=await db.from("activities").select("*").order("sort_order",{ascending:true}).order("created_at",{ascending:true});if(error){$("#adminActivityList").textContent=error.message;return}activities=data||[];renderActivities()}
function renderActivities(){$("#adminActivityList").innerHTML=activities.map(x=>`<div class="admin-item"><div><strong>${escapeHTML(x.number_label||"")} ${escapeHTML(x.title)}</strong><div>${escapeHTML(x.description)}</div><small>Thứ tự: ${x.sort_order}</small></div><div class="admin-actions"><button class="small-btn" data-activity-edit="${x.id}">Sửa</button><button class="small-btn danger" data-activity-delete="${x.id}">Xóa</button></div></div>`).join("")||"<p>Chưa có hoạt động.</p>"}
function editActivity(id){const x=activities.find(v=>v.id===id);if(!x)return;$("#activityId").value=x.id;$("#activityNumber").value=x.number_label||"";$("#activityTitle").value=x.title;$("#activityImage").value=x.image||"";$("#activityDescription").value=x.description;$("#activityOrder").value=x.sort_order;document.querySelector('#activityForm').scrollIntoView({behavior:'smooth',block:'center'})}
async function saveActivity(e){e.preventDefault();const id=$("#activityId").value;const payload={number_label:$("#activityNumber").value.trim(),title:$("#activityTitle").value.trim(),description:$("#activityDescription").value.trim(),image:$("#activityImage").value.trim(),sort_order:Number($("#activityOrder").value)||0,updated_at:new Date().toISOString()};const {error}=id?await db.from("activities").update(payload).eq("id",id):await db.from("activities").insert(payload);if(error){alert(error.message);return}resetActivity();await loadActivities()}
function resetActivity(){$("#activityForm").reset();$("#activityId").value="";$("#activityOrder").value=1}
async function deleteActivity(id){if(!confirm("Xóa hoạt động này?"))return;const {error}=await db.from("activities").delete().eq("id",id);if(error)alert(error.message);else loadActivities()}

$("#loginForm").addEventListener("submit",login);
$("#logoutBtn").addEventListener("click",async()=>{await db.auth.signOut();location.reload()});
$("#shelterForm").addEventListener("submit",saveShelter);$("#cancelEdit").addEventListener("click",resetForm);
$("#saveContactEmail").addEventListener("click",saveContactEmail);
$("#projectForm").addEventListener("submit",saveProject);
$("#journeyForm").addEventListener("submit",saveJourney);$("#cancelJourney").addEventListener("click",resetJourney);
$("#activityForm").addEventListener("submit",saveActivity);$("#cancelActivity").addEventListener("click",resetActivity);$("#teamForm").addEventListener("submit",saveTeamMember);$("#cancelTeam").addEventListener("click",resetTeam);
$("#adminShelterList").addEventListener("click",e=>{if(e.target.dataset.edit)editShelter(Number(e.target.dataset.edit));if(e.target.dataset.delete)deleteShelter(Number(e.target.dataset.delete))});
$("#volunteerList").addEventListener("click",async e=>{const id=e.target.dataset.volunteerDelete;if(id&&confirm("Xóa đăng ký này?")){const {error}=await db.from("volunteers").delete().eq("id",id);if(error)alert(error.message);else loadVolunteers()}});
$("#adminJourneyList").addEventListener("click",e=>{if(e.target.dataset.journeyEdit)editJourney(Number(e.target.dataset.journeyEdit));if(e.target.dataset.journeyDelete)deleteJourney(Number(e.target.dataset.journeyDelete))});
$("#adminActivityList").addEventListener("click",e=>{if(e.target.dataset.activityEdit)editActivity(Number(e.target.dataset.activityEdit));if(e.target.dataset.activityDelete)deleteActivity(Number(e.target.dataset.activityDelete))});
$("#adminTeamList").addEventListener("click",e=>{if(e.target.dataset.teamEdit)editTeamMember(Number(e.target.dataset.teamEdit));if(e.target.dataset.teamDelete)deleteTeamMember(Number(e.target.dataset.teamDelete))});
(async()=>{if(await ensureAdmin())await refresh()})();
