-- NHỊP CẦU YÊU THƯƠNG
-- Website công khai: người dùng chỉ xem + đăng ký tình nguyện.
-- Trang admin.html: chỉ tài khoản có role='admin' mới được thêm/sửa/xóa dữ liệu.

create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'user' check (role in ('user','admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.shelters (
  id bigint generated by default as identity primary key,
  name text not null,
  location text not null,
  category text not null check (category in ('food','medical','volunteer','supplies')),
  tag text,
  image text,
  description text not null,
  need text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.volunteers (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  name text not null,
  email text not null,
  help text not null,
  message text,
  created_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  id integer primary key check (id=1),
  contact_email text not null default 'hello@example.com',
  updated_at timestamptz not null default now()
);
insert into public.site_settings(id,contact_email) values (1,'hello@example.com') on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.shelters enable row level security;
alter table public.volunteers enable row level security;
alter table public.site_settings enable row level security;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=auth.uid() and role='admin');
$$;

-- PROFILE: admin page chỉ cần đọc role của chính mình.
drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select to authenticated using (id=auth.uid() or public.is_admin());
drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles for insert to authenticated with check (id=auth.uid());

-- SHELTERS: ai cũng được xem, chỉ admin được thay đổi.
drop policy if exists "shelters_public_read" on public.shelters;
create policy "shelters_public_read" on public.shelters for select to anon,authenticated using (true);
drop policy if exists "shelters_admin_insert" on public.shelters;
create policy "shelters_admin_insert" on public.shelters for insert to authenticated with check (public.is_admin());
drop policy if exists "shelters_admin_update" on public.shelters;
create policy "shelters_admin_update" on public.shelters for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "shelters_admin_delete" on public.shelters;
create policy "shelters_admin_delete" on public.shelters for delete to authenticated using (public.is_admin());

-- VOLUNTEERS: người dùng không cần đăng nhập để gửi; chỉ admin được xem/xóa.
drop policy if exists "volunteers_public_insert" on public.volunteers;
create policy "volunteers_public_insert" on public.volunteers for insert to anon,authenticated with check (user_id is null or user_id=auth.uid());
drop policy if exists "volunteers_admin_read" on public.volunteers;
create policy "volunteers_admin_read" on public.volunteers for select to authenticated using (public.is_admin());
drop policy if exists "volunteers_admin_delete" on public.volunteers;
create policy "volunteers_admin_delete" on public.volunteers for delete to authenticated using (public.is_admin());

-- EMAIL LIÊN HỆ: ai cũng được đọc; chỉ admin được sửa.
drop policy if exists "settings_public_read" on public.site_settings;
create policy "settings_public_read" on public.site_settings for select to anon,authenticated using (true);
drop policy if exists "settings_admin_update" on public.site_settings;
create policy "settings_admin_update" on public.site_settings for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "settings_admin_insert" on public.site_settings;
create policy "settings_admin_insert" on public.site_settings for insert to authenticated with check (public.is_admin());

-- DỮ LIỆU MẪU
insert into public.shelters (name,location,category,tag,image,description,need)
select * from (values
('Trại Hy Vọng','TP. Hồ Chí Minh','food','ĐANG CẦN','https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=900&q=80','Cứu hộ chó mèo bị bỏ rơi và chăm sóc trong thời gian tìm mái ấm.','Thức ăn hạt, pate và chi phí chăm sóc.'),
('Mái Ấm Mèo Nhỏ','Bình Dương','medical','CẦN Y TẾ','https://images.unsplash.com/photo-1519052537078-e6302a4968d4?auto=format&fit=crop&w=900&q=80','Mái ấm chuyên chăm sóc mèo bị bệnh hoặc bị thương.','Thuốc, vật tư y tế và hỗ trợ viện phí.'),
('Mái Nhà Cơ Hội Mới','Đồng Nai','volunteer','CẦN TÌNH NGUYỆN','https://images.unsplash.com/photo-1450778869180-41d0601e046e?auto=format&fit=crop&w=900&q=80','Không gian tạm trú cho chó mèo chờ được nhận nuôi.','Tình nguyện viên cuối tuần và người hỗ trợ vận chuyển.')
) as x(name,location,category,tag,image,description,need)
where not exists (select 1 from public.shelters);

-- TẠO ADMIN:
-- 1) Trong Supabase Authentication > Users, tạo tài khoản admin.
-- 2) Lấy UUID của user đó.
-- 3) Chạy:
-- update public.profiles set role='admin' where id='UUID_ADMIN';
-- Admin truy cập: https://f5nhipcauyeuthuong.github.io/Nhip-Cau-Yeu-Thuong/admin.html

-- Cho trang công khai lấy tổng số lượt đăng ký mà không đọc dữ liệu cá nhân.
create or replace function public.get_public_volunteer_count()
returns bigint language sql stable security definer set search_path=public as $$
  select count(*) from public.volunteers;
$$;
grant execute on function public.get_public_volunteer_count() to anon, authenticated;

-- NỘI DUNG CÓ THỂ CHỈNH SỬA TỪ TRANG ADMIN
create table if not exists public.project_content (
  id integer primary key check (id=1),
  title text not null,
  content text not null,
  image text,
  tags text[] not null default '{}',
  updated_at timestamptz not null default now()
);

create table if not exists public.journey_items (
  id bigint generated by default as identity primary key,
  number_label text,
  title text not null,
  description text not null,
  image text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  number_label text,
  title text not null,
  description text not null,
  image text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Thêm cột ảnh cho các nội dung đã tạo từ phiên bản trước
alter table public.project_content add column if not exists image text;
alter table public.journey_items add column if not exists image text;
alter table public.activities add column if not exists image text;

alter table public.project_content enable row level security;
alter table public.journey_items enable row level security;
alter table public.activities enable row level security;

drop policy if exists "project_public_read" on public.project_content;
create policy "project_public_read" on public.project_content for select to anon,authenticated using (true);
drop policy if exists "project_admin_insert" on public.project_content;
create policy "project_admin_insert" on public.project_content for insert to authenticated with check (public.is_admin());
drop policy if exists "project_admin_update" on public.project_content;
create policy "project_admin_update" on public.project_content for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "project_admin_delete" on public.project_content;
create policy "project_admin_delete" on public.project_content for delete to authenticated using (public.is_admin());

drop policy if exists "journey_public_read" on public.journey_items;
create policy "journey_public_read" on public.journey_items for select to anon,authenticated using (true);
drop policy if exists "journey_admin_insert" on public.journey_items;
create policy "journey_admin_insert" on public.journey_items for insert to authenticated with check (public.is_admin());
drop policy if exists "journey_admin_update" on public.journey_items;
create policy "journey_admin_update" on public.journey_items for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "journey_admin_delete" on public.journey_items;
create policy "journey_admin_delete" on public.journey_items for delete to authenticated using (public.is_admin());

drop policy if exists "activities_public_read" on public.activities;
create policy "activities_public_read" on public.activities for select to anon,authenticated using (true);
drop policy if exists "activities_admin_insert" on public.activities;
create policy "activities_admin_insert" on public.activities for insert to authenticated with check (public.is_admin());
drop policy if exists "activities_admin_update" on public.activities;
create policy "activities_admin_update" on public.activities for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "activities_admin_delete" on public.activities;
create policy "activities_admin_delete" on public.activities for delete to authenticated using (public.is_admin());

insert into public.project_content(id,title,content,tags)
values (1,
'Một nơi để biết về những sinh mệnh đang cần một mái ấm.',
'Website được xây dựng như một cây cầu giữa cộng đồng và các trại cứu hộ. Người dùng có thể xem thông tin, tìm trại phù hợp, đọc nhu cầu hiện tại và chọn một cách hỗ trợ phù hợp.',
array['Minh bạch','Dễ tiếp cận','Cộng đồng'])
on conflict (id) do nothing;

insert into public.journey_items(number_label,title,description,sort_order)
select * from (values
('01','Kết nối','Tập hợp thông tin các trại và nhu cầu hỗ trợ.',1),
('02','Chia sẻ','Đưa câu chuyện và thông tin cần thiết đến cộng đồng.',2),
('03','Hành động','Tiếp nhận đăng ký và kết nối người hỗ trợ với đúng nơi cần giúp.',3)
) as x(number_label,title,description,sort_order)
where not exists (select 1 from public.journey_items);

insert into public.activities(number_label,title,description,sort_order)
select * from (values
('01','Khám phá','Tìm hiểu các trại cứu hộ, hoàn cảnh và nhu cầu hiện tại.',1),
('02','Chọn cách hỗ trợ','Bạn có thể tình nguyện, đóng góp vật dụng hoặc hỗ trợ theo nhu cầu của từng trại.',2),
('03','Chung tay','Gửi đăng ký và kết nối với cộng đồng để biến một hành động nhỏ thành thay đổi thật.',3)
) as x(number_label,title,description,sort_order)
where not exists (select 1 from public.activities);

-- THÀNH VIÊN NHÓM: có thể thêm/sửa/xóa từ trang admin
create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null,
  image text,
  bio text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.team_members enable row level security;

drop policy if exists "team_public_read" on public.team_members;
create policy "team_public_read" on public.team_members for select to anon,authenticated using (true);
drop policy if exists "team_admin_insert" on public.team_members;
create policy "team_admin_insert" on public.team_members for insert to authenticated with check (public.is_admin());
drop policy if exists "team_admin_update" on public.team_members;
create policy "team_admin_update" on public.team_members for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "team_admin_delete" on public.team_members;
create policy "team_admin_delete" on public.team_members for delete to authenticated using (public.is_admin());

insert into public.team_members(name,role,image,bio,sort_order)
select 'Nhóm Nhịp Cầu Yêu Thương','Thiết kế · Nội dung · Công nghệ · Kết nối cộng đồng',null,'Nhóm thực hiện dự án Nhịp Cầu Yêu Thương.',1
where not exists (select 1 from public.team_members);
